config/routes.rb
Rails.application.routes.draw do

  get 'items/index/:cat_id', to: 'items#index', as: 'items_root'

  get 'items/show/:id', to: 'items#show', as: 'item_show'

  get 'items/search', to: 'items#search', as: 'items_search'

  get 'persons/profile'

  post 'order', to: 'order#add_item', as: 'order_item_add'
  delete 'order', to: 'order#delete_item', as: 'order_item_delete'

  get 'make_order', to: 'make_order#index', as: 'make_order'

  get 'cart', to: 'order#cart', as: 'cart'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'index#index'
  get 'persons/profile', as: 'user_root'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :orders

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_and_belongs_to_many :items
  belongs_to :user
  accepts_nested_attributes_for :items

  def total_price
    full_price = 0
      if self.items
        self.items.each do |item|
          full_price += item.price
        end
      end

    return full_price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :store_location

  before_filter :set_user_cookie

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def set_user_cookie
    if !cookies[:cart_id]
      cookies[:cart_id] = Base64.encode64(DateTime.now.to_s)
    end
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @items = Item.where(show_on_main: true)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_pages

  def index
    if !params[:search_string]
      @items = Item.where(category_id: params[:cat_id]).paginate(:page => params[:page], :per_page => @per_page).order("#{@sort_by} ASC")
    else
      @search = params[:search_string]
      @items = Item.where("name LIKE ? AND category_id = ?" , "%#{@search}%", params[:cat_id]).paginate(:page => params[:page], :per_page => @per_page).order("#{@sort_by} ASC")
    end

    @category = Category.find(params[:cat_id])
  end

  def search
    @search = params[:search_string]
    @items = Item.where("name LIKE ?" , "%#{@search}%").paginate(:page => params[:page], :per_page => @per_page).order("#{@sort_by} ASC")
    render 'index'
  end

  def show
    @item = Item.find(params[:id])
  end

  def set_pages
    @pages_count = [3,6,9,12]
    !params[:per_page] ? @per_page = 9 : @per_page = params[:per_page].to_i
    params[:sort_by] ? @sort_by = params[:sort_by] : @sort_by = 'name'
  end
end

app/controllers/make_order_controller.rb
class MakeOrderController < ApplicationController
  before_filter :authenticate_user!

  def index
    current_order = Order.where(session_id: cookies[:cart_id], is_finished: false).first
    user = current_user
    OrderMailer.order_email(user, current_order)
о    current_order.update_attribute(:is_finished, true)
    cookies[:cart_id] = Base64.encode64(DateTime.now.to_s)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def add_item
    current_order = Order.find_or_create_by(session_id: cookies[:cart_id], is_finished: false)
    item_to_add = Item.find(params[:item_id])
    current_order.items << item_to_add
    current_order.save

    @response = [:status => 'success']
    respond_to do |format|
      format.json { render :json => @response }
    end
  end

  def cart
    current_orders = Order.where(session_id: cookies[:cart_id], is_finished: false)
    current_order = current_orders[0]
    @full_price = 0
    if current_order
      if current_order.items
        @full_price = current_order.total_price
        @items = current_order.items
      end
    end
  end

  def delete_item
    item_to_delete = Item.find(params[:item_id])
    current_orders = Order.where(session_id: cookies[:cart_id], is_finished: false)
    current_order = current_orders[0]
    current_order.items.delete(item_to_delete)

    @response = [:status => 'success', :item_id => item_to_delete.id]
    respond_to do |format|
      format.json { render :json => @response }
    end
  end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
   <div class="alert alert-danger alert-dismissable"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
    HTML

    html.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/make_order_helper.rb
module MakeOrderHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/index/index.html.erb
  <div class="row carousel-holder">

    <div class="col-md-12">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="item active">
            <img class="slide-image" src="http://placehold.it/800x300" alt="">
          </div>
          <div class="item">
            <img class="slide-image" src="http://placehold.it/800x300" alt="">
          </div>
          <div class="item">
            <img class="slide-image" src="http://placehold.it/800x300" alt="">
          </div>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>

  </div>

  <div class="row">
    <% @items.each do |item| %>
    <div class="col-sm-4 col-lg-4 col-md-4">
      <div class="thumbnail">
        <%= image_tag item.image.url(:thumb) %>

        <div class="caption">
          <h4 class="pull-right"><%= item.price %> $</h4>
          <h4><a href="<%= item_show_path(item.id)%>"><%= item.name %></a>
          </h4>

          <p><%= item.short_description %>
            <a  href="<%= item_show_path(item.id)%>">more</a></p>
        </div>
      </div>
    </div>
    <% end %>

  </div>

app/views/items/index.html.erb
<h2>
  <% if @category %>
    <%= @category.name %>
  <% else %>
    Search
  <% end %>
</h2>
<div class="row">
    <form method="GET" >
        Items on page:
        <select name="per_page" onchange="this.form.submit()">
          <% @pages_count.each do |num| %>
            <option <% if ( @per_page == num ) %>selected<% end %> ><%= num %></option>
          <% end %>
        </select>
        Sort By:
        <select name="sort_by" onchange="this.form.submit()">
            <option value="name" <% if ( @sort_by == 'name' ) %>selected<% end %> >Name</option>
            <option value="price" <% if ( @sort_by == 'price' ) %>selected<% end %>>Price</option>
        </select>
        Search:
        <input type="text" name="search_string" value="<%= @search %>" />
        <input type="submit" value="Search"  />
    </form>
</div>
<div class="row">
  <% @items.each do |item| %>
      <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
          <%= image_tag item.image.url(:thumb) %>

          <div class="caption">
            <h4 class="pull-right"><%= item.price %> $</h4>
            <h4><a href="<%= item_show_path(item.id)%>"><%= item.name %></a>
            </h4>

            <p><%= item.short_description %>
              <a  href="<%= item_show_path(item.id)%>">more</a></p>
          </div>
        </div>
      </div>
  <% end %>

</div>

<%= will_paginate @posts %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<%= image_tag @item.image.url(:medium) %>
<p>Price: <%= @item.price %> $</p>

<input type="button" value="Buy" class="btn btn-info buy_button"/>

<script>
  $('.buy_button').click(function() {
      $.ajax({
          method: "POST",
          url: "<%= order_item_add_path %>.json",
          context: document.body,
          dataType: 'json',
          data: {
            'item_id': <%= @item.id %>
          }
      }).done(function() {
          $('.buy_button').val("done");
          $('.buy_button').attr('disabled','disabled');
      });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyShop</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">RubyShop</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="<%= items_search_path %>">Search</a>
        </li>
        <li>
            <a href="<%= cart_path %>">Cart</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                <i class="glyphicon glyphicon-user"></i> <%= current_user.email %> <span class="caret"></span></a>
              <ul id="g-account-menu" class="dropdown-menu" role="menu">
                <li><a href="<%= user_root_path %>">My Profile</a></li>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to('Sign In', new_user_session_path) %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<div class="container">
  <div class="row">

    <div class="col-md-3">
      <p class="lead">Shop Name</p>

      <div class="list-group">
        <% Category.all.each do |category| %>
        <a href="<%= items_root_path(category.id) %>" class="list-group-item"><%= category.name %></a>
        <% end %>
      </div>
    </div>
    <div class="col-md-9">
        <%= yield %>
    </div>

  </div>
</div>

<div class="container">

  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Your Website 2014</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->
</body>
</html>

app/views/make_order/index.html.erb
<h3>Your order completed successfully</h3>

app/views/order/cart.html.erb
<h3>Shopping cart</h3>

<% if @items %>
<table class="table table-striped">
  <tbody>
    <% @items.each_with_index do |item, index| %>
        <tr id="item_tr_<%= item.id %>">
          <td><%= index + 1 %></td>
          <td><%= item.name %></td>
          <td><%= item.price %>$</td>
          <td><a href="#" item_id="<%= item.id %>" class="delete_button" ><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
        </tr>
    <% end %>
  </tbody>
</table>
Total price: <%= @full_price %>$

<form action="<%= make_order_path %>">
    <input type="submit" class="btn btn-info" value="Make Order" />
</form>
<% else %>
    You currently don't have items to buy
<% end %>



<script>
    $('.delete_button').click(function() {
        var item_id = $(this).attr('item_id');
        $.ajax({
            method: "DELETE",
            url: "<%= order_item_delete_path %>.json",
            context: document.body,
            dataType: 'json',
            data: {
                'item_id': item_id
            }
        }).done(function( data ) {
            $('#item_tr_' + data[0].item_id).hide();
        });
    });
</script>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>